### ISSUE TITLE
flickr复现

### ISSUE THREAD

**Issue by qingyi3** [yimutianyang/HGSR#1]
您好，感谢你们为该领域做出的巨大贡献。我在尝试复现flickr数据集的实验时，发现Recall@10和NDCG@10的结果分别只有0.005和0.0047，与论文中的结果相差较大。不过，其他实验结果与论文中相符。能否请您分享一下flickr数据集下复现的具体细节，包括超参数设置等，以便更好地复现实验结果？非常感谢您的帮助。
![QQ图片20240726201325](https://github.com/user-attachments/assets/6f6d9a73-b818-4ed8-9853-b48202b291ec)

**Comment by yimutianyang** [comment]
您好，感谢对我们工作的关注~
请问下flickr数据集在test阶段(run_hgsr.py line 119)topk分开评估的结果是多少？
是评估代码的bug，在flickr数据集上多个topk同时评估时，会低一些。
有问题欢迎继续讨论

**Comment by qingyi3** [comment]
> 您好，感谢对我们工作的关注~ 请问下flickr数据集在test阶段(run_hgsr.py line 119)topk分开评估的结果是多少？ 是评估代码的bug，在flickr数据集上多个topk同时评估时，会低一些。 有问题欢迎继续讨论

非常感谢作者大大的解答，实验测试结果符合预期，再次感谢你们为该领域做出的巨大贡献。

**Comment by yimutianyang** [comment]
好的，不客气~
